### ISSUE TITLE
Getting `pub: command not found` after using setup-dart within Github Actions

### ISSUE THREAD

**Issue by dshukertjr** [dart-lang/setup-dart#46]
I had been using this action for some time now, and everything was working fine until today I noticed that my actions were failing. 

I have not changed the action yaml file, so was wondering what could be causing this error. 

Here is the action file that I am using:

```yaml
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }} / SDK ${{ matrix.sdk }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["12"]
        sdk: [stable, beta, dev]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: pub get
```

This action fails with the following error:

```sh
/home/runner/work/_temp/f9745214-a5f6-41e6-a039-c51f64d69379.sh: line 1: pub: command not found
Error: Process completed with exit code 127.
```

You can find the actual action file [here](https://github.com/supabase-community/gotrue-dart/blob/main/.github/workflows/main.yml)

You can also find the failing Github action [here](https://github.com/supabase-community/gotrue-dart/runs/5187352274?check_suite_focus=true).
