### ISSUE TITLE
Specifying 2.12.0 version in Github actions waits indefinitely

### ISSUE THREAD

**Issue by dshukertjr** [dart-lang/setup-dart#61]
I am trying to test my code against v2.12.0 of Dart, but specifying the version in Github Actions just waits with the following output until it times out, and was wondering if this is a temporary server issue, or is an issue of this action. 

```bash
Attempt:480 waiting for isolate vm-isolate to check in
Attempt:480 waiting for isolate dartdev to check in
```

```yaml
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test / SDK ${{ matrix.sdk }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: ["12"]
        sdk: [2.12.0, stable, beta, dev]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: dartfmt
        run: dart format lib test -l 80 --set-exit-if-changed

      - name: analyzer
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: Run tests
        run: dart test

```
