### ISSUE TITLE
I can't use the `publish` workflow to publish flutter packages

### ISSUE THREAD

**Issue by ricardodalarme** [dart-lang/setup-dart#87]
## Description

I'm trying to integrate this workflow with my Flutter package, but when I do, I get the following error:

```
Run dart pub get
Resolving dependencies...
Because flutter_card_swiper requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`.
Error: Process completed with exit code 1.
```

**Comment by ricardodalarme** [comment]
I also tried to do it manually, but it got stuck on the authorization step

![image](https://user-images.githubusercontent.com/35314270/227520043-705c1eb3-9cff-4329-b340-724d7500967d.png)

```
name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get all Flutter Packages
        run: flutter pub get

      - name: Publish
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

```
